accounts/urls.py
from django.urls import path



from . import views

app_name="accounts"

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile' ),
    path('add/user/', views.CreateUserView.as_view(), name='create_user'),
    path('user/list/', views.UsersListView.as_view(), name='user_list'),
    path('user/<int:pk>/detail', views.UserDetailView.as_view(), name='user_details'),
    path('user/<int:pk>/edit', views.UpdateUserView.as_view(), name='user_update'),
]

crm_blog/urls.py
from django.urls import path
from . import views

app_name = 'crm_blog'

urlpatterns = [
    path('home/', views.blog_home_view, name='home'),
]

marketing/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.forms import AuthenticationForm

#from accounts.urls import user_login, user_logout
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard', include( 'jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('marketing/', include('crm_blog.urls'),),
    path('center/', include('centermanager.urls'),),
    path('contacts/', include('contacts.urls')),
    path('accounts/', include('accounts.urls'),),
    path('schedule/', include('activitycalendar.urls')),
    path('marketinghead/', include('marketinghead.urls')),
    path('activity/', include('careerconsultant.urls')),
    path('activity1/', include('activity.urls')),
    path('centerbusinessmanager/', include('centerbusinessmanager.urls')),
    path('registrar/',include('registrar.urls')),
    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketinghead/urls.py
from django.urls import path


from . import views

app_name = 'marketing_head'

urlpatterns = [
    path('collateral/request/', views.collateral_request, name='collateral_request'),
    path('budget/request/', views.budget_request, name='budget_request'),
    
    path('budget/list/', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/create/', views.BudgetCreateView.as_view(), name='budget'),
    path('budget/detail/<int:pk>/', views.BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/update/<int:pk>/', views.BudgetUpdateView.as_view(), name='budget_update'),
    
    
    path('collateral/list/', views.CollateralListView.as_view(), name='collateral_list'),
    path('create/collateral/', views.CollateralCreateView.as_view(), name='create_collateral'),
    path('collateral/detail/<int:pk>/', views.CollateralDetailView.as_view(), name='collateral_detail'),
    path('collateral/edit/<int:pk>/', views.CollateralUpdateView.as_view(), name='collateral_update'),
    
    
    path('assign-quota/', views.CreateAssignQuota.as_view(), name='assign_quota'),
    path('quota/list/', views.AssignQuotaListView.as_view(), name='assign_list'),
    path('quota/<int:pk>/view/', views.AssignQuotaDetailView.as_view(), name='view_quota'),
    path('quota/<int:pk>/edit/', views.AssignQuotaUpdateView.as_view(), name='quota_update'),
    
    
    path('assign-territory/', views.TerritoryAssign.as_view(), name='add_territory'),
    path('territory/list/', views.TerritoryListView.as_view(), name='a_list'),
    path('territory/edit/<int:pk>/', views.TerritoryUpdateView.as_view(), name='a_edit'),
]

marketinghead/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.http import JsonResponse
from django.contrib import messages
from django.views.generic import (
    CreateView, UpdateView, DetailView, TemplateView, View)
from django.urls import reverse
from django.db.models import Q
from django.template.loader import render_to_string
from marketinghead.models import Budget, Collateral, AssignQuota, AssignTerritory
from centermanager.models import TargetSheet
from marketinghead.forms import BudgetForm, CollateralForm, AssignQuotaForm, AssignTerritoryForm
from accounts.models import User
from django.core.exceptions import PermissionDenied
from django.db.models import Sum


def budget_request(request):
    return render(request, 'budget/budget_request.html')

def collateral_request(request):
    return render(request, 'collateral/collateral_request.html')
#-------------------------------------------------------------------

class AssignQuotaListView(LoginRequiredMixin, TemplateView):
    model = AssignQuota
    context_object_name = 'assign_obj_list'
    template_name = 'quota/quota_list.html'

    def get_queryset(self):
        queryset = self.model.objects.all()

        if(self.request.user.is_marketinghead):
            queryset = queryset.filter(
                Q(assigned_to__in=[self.request.user]) |
                Q(created_by=self.request.user)
            )
        request_post = self.request.POST
        if request_post:
            if request_post.getlist('assigned_to'):
                queryset = queryset.filter(
                    assigned_to__id__in=request_post.getlist('assigned_to')
                )
            return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super(AssignQuotaListView, self).get_context_data(**kwargs)
        context['assign_obj_list'] = self.get_queryset()
        quota = AssignQuota.objects.all()
        context['quota'] = quota
        target = TargetSheet.objects.all()
        context['targetsheet'] = target

        context['assignedto_list'] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i
        ]
        search = False
        if(
            self.request.POST.get(
                'email'
            ) or self.request.POST.get('assigned_to')
        ):
            search = True
        context['search'] = search

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class CreateAssignQuota(LoginRequiredMixin, CreateView):
    model = AssignQuota
    form_class = AssignQuotaForm
    template_name = 'quota/create_quota.html'
    context_object_name = 'assign_list'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_marketinghead:
            self.users = User.objects.filter(is_active=True).order_by('email')
        else:
            self.users = User.objects.filter(
                is_marketinghead=True).order_by('email')
        return super(CreateAssignQuota, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreateAssignQuota, self).get_form_kwargs()
        if self.request.user.is_marketinghead:
            self.users = User.objects.filter(is_active=True).order_by('email')
            kwargs.update({"assigned_to": self.users})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            assign_quota_obj = form.save(commit=False)
            assign_quota_obj.created_by = self.request.user
            assign_quota_obj.save()
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        assign_quota_obj = form.save(commit=False)
        if self.request.POST.getlist('assigned_to', []):
            assign_quota_obj.assigned_to.add(*self.request.POST.getlist('assigned_to'))

        assigned_to_list = list(assign_quota_obj.assigned_to.all().values_list('id', flat=True))
        current_site = get_current_site(self.request)

        if self.request.is_ajax():
            return JsonResponse({'error': False})

        if self.request.POST.get("savenewform"):
            return redirect("marketing_head:assign_quota")

        return redirect("marketing_head:assign_list")

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse(
                {
                    'error': True,
                    'quota_errors': form.errors
                }
            )
        return self.render_to_response(
            self.get_context_data(form=form)
        )

    def get_context_data(self, **kwargs):
        context = super(CreateAssignQuota, self).get_context_data(**kwargs)
        context['quota_form'] = context['form']
        context['users'] = self.users
        context['assignedto_list'] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i
        ]
        context['assign_list'] = self.get_queryset()
        quota = AssignQuota.objects.all()
        context['quota_list'] = quota
        target = TargetSheet.objects.all()
        context['targetsheet'] = target

        return context


class AssignQuotaDetailView(LoginRequiredMixin, DetailView):
    model = AssignQuota
    context_object_name = 'quota_record'
    template_name = "quota/quota_detail.html"

    def get_object(self):
        obj = super().get_object
        if self.request.user.is_marketinghead:
            AssignQuota.objects.get_or_create(user=self.request.user)

        return obj

    def get_context_data(self, **kwargs):
        context = super(AssignQuotaDetailView, self).get_context_data(**kwargs)
        user_assign_list = [
            assigned_to.id for assigned_to in context['object'].assigned_to.all()
        ]
        user_assigned_accounts = set(
            self.request.user.account_assigned_users.values_list('id', flat=True))
        if user_assigned_accounts.intersection(contact_accounts):
            user_assign_list.append(self.request.user.id)

        if self.request.user == context['object'].created_by:
            user_assign_list.append(self.request.user.id)

        assigned_data = []
        for each in context['quota_record'].assigned_to.all():
            assigned_dict = {}
            assigned_dict['id'] = each.id
            assigned_dict['name'] = each.email
            assigned_data.append(assigned_dict)

        if self.request.user.is_marketinghead:
            users_mention = list(User.objects.filter(
                is_active=True).values('last_name'))
        elif self.request.user != context['object'].created_by:
            users_mention = [
                {'last_name': context['object'].created_by.last_name}]
        else:
            users_mention = list(
                context['object'].assigned_to.all().values('last_name'))

        context.update({
            "assigned_data": json.dumps(assigned_data),
            'users_mention': user_mention,
        })

        return context


class AssignQuotaUpdateView(LoginRequiredMixin, UpdateView):
    model = AssignQuota
    form_class = AssignQuotaForm
    tempalte_name = "quota/create_quota.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_marketinghead:
            self.users = User.objects.filter(
                is_marketinghead=True).order_by('email')
        else:
            self.users = User.objects.filter(
                is_marketinghead=True).order_by('email')
        return super(AssignQuotaUpdateView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(AssignQuotaUpdateView, self).get_form_kwargs()
        if self.request.user.is_marketinghead:
            self.users = User.objects.filter(is_active=True).order_by('email')
            kwargs.update({'assigned_to': self.users})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            assign_quota_obj = form.save(commit=False)
            assign_quota_obj.save()
            return self.form_valid(form)

    def form_valid(self, form):
        assigned_to_ids = self.get_object().assigned_to_all().values_list('id', flat=True)
        assign_quota_obj = form.save(commit=False)
        previous_assigned_to_users = list(assign_quota_obj.assigned_to.all().values_list('id', flat=True))
        all_members_list = []
        if self.request.POST.getlist('assigned_to', []):
            current_site = get_current_site(self.request)
            assigned_form_users = form.cleaned_data.get(
                'assigned_to'
            ).values(list('id', flat=True))
            all_members_list = list(
                set(list(assigned_form_users)) - set(list(assigned_to_ids))
            )
            assign_quota_obj.assigned_to.clear()
            assign_quota_obj.assigned_to.add(
                *self.request.POST.getlist('assigned_to')
            )
        else:
            assign_quota_obj.assigned_to.clear()

        current_site = get_current_site(self.request)
        assigned_to_list = list(
            assign_quota_obj.assigned_to.all().values_list('id', flat=True))
        recipients = list(set(assigned_to_list) -
                          set(previous_assigned_to_users))

        def get_context_data(self, **kwargs):
            context = super(AssignQuotaUpdateView,
                            self), get_context_data(**kwargs)
            context['assign_quota_obj'] = self.object
            user_assign_list = [
                assigned_to.id for assigned_to in context['assign_quota_obj'].assigned_to.all()
            ]

marketinghead/templates/budget/budget_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header %}
{% include 'header.html' %}
{% endblock header %}

{% block sidebar %}

{% endblock sidebar %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block title %}
<title>Marketing | Target Sheet</title>
{% endblock title %}


{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{% url 'crm_blog:home' %}" class="btn btn-primary"> BACK</a>

        <div class="float-left">

        </div>
    </div>
    <!---->
    <div class="card">

        <div class="card-body">
            <!-- Start of Breadcrumb -->
            <nav aria-label="breadcrumb" class="row align-items-center justify-content-between"
                style="padding-top:2%; padding-right:2%; padding-left:2%;">
                <h5 class=" mb-0 text-gray-800">School Year: </h5>
                <div class="row float-right">
                    <div class="d-sm-flex align-items-center mr-2">
                        <a href="{% url 'marketing_head:budget_request' %}" class="btn btn-primary"> VIEW REQUEST</a>
                    </div>
                    {% if request.user.is_marketinghead %}
                <div class="d-sm-flex align-items-center">
                    <a href="{% url 'marketing_head:budget' %}" class="btn btn-primary"> ADD BUDGET</a>
                </div>
                {% endif %}
            </div>

                
            </nav>



            <!-- end -->

            <!-- End of Bread Crumb -->
            <br>

            <!-- page content -->
            <div class="content-section">
                {% include 'messages.html' %}

                <div class="row d-flex justify-content-center" style="min-height:50%;">
                    
                    <!-- Retail -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-info shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Budget
                                            of school year</div>
                                        <div class="row no-gutters align-items-center">

                                            {% for budget_list in budget %}
                                            <div class="col-auto">
                                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                                    {{ budget_list.amount }}</div>
                                            </div>
                                            {% endfor %}
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Retail -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Available
                                            Budget</div>
                                        <div class="row no-gutters align-items-center">

                                            {% for budget_list in budget %}
                                            <div class="col-auto">
                                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                                    {{ budget_list.amount }}</div>
                                            </div>
                                            {% endfor %}
                                          
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Retail -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-success shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Used
                                            Budget</div>
                                        <div class="row no-gutters align-items-center">

                                            {% for budget_list in budget %}
                                            <div class="col-auto">
                                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                                    {{ budget_list.amount }}</div>
                                            </div>
                                            {% endfor %}
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>
                <nav aria-label="Page navigation example" style="margin-button: 1%; padding-left: 84%;">
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
                <!---->
                <center>
                    <div style="max-width:80%">
                        <table class="table table-bordered" style="height: 100%;">
                            <thead class="bg-primary text-light">
                                <tr>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Date of Arrival</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            {% for budget_list in budget %}
                            <tbody>
                                <tr>
                                    <th scope="row">{{ budget_list.amount }}</th>
                                    <td>{{ budget_list.arrival }}</td>
                                    <td>
                                        <a href="{% url 'marketing_head:budget_update' budget_list.pk %}" class="btn btn-success" style="padding: 3px;">UPDATE</a>
                                    </td>
                                </tr>
                            </tbody>
                            {% endfor %}

                        </table>
                    </div>
                </center>
            </div>
        </div>
    </div>
</div>
<br>















{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

marketinghead/templates/budget/budget_request.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header %}
{% include 'header.html' %}
{% endblock header %}

{% block sidebar %}

{% endblock sidebar %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block title %}
        <title>Marketing | Target Sheet</title>
{% endblock title %}


{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{% url 'marketing_head:collateral_list' %}" class="btn btn-primary" > BACK</a>
      
<div class="float-left">
 
</div>
</div>
<!---->
<div class="card" style="height: 50%;">

      <div class="card-body " style="min-height: 30vw;">

<br><br>
    
<!-- page content -->
    <div class="content-section">
        {% include 'messages.html' %}
        <center>
            <div style="max-width:90%">
              <table class="table table-bordered" style="height: 100%;">
                <thead class="bg-primary text-light">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Activity Name</th>
                    <th>Amount</th>
                    <th scope="col">Details</th>
                    <th scope="col">Submitted by</th>
                    {% if request.user.is_marketinghead or request.user.is_centermanager %}
                    <th scope="col">Remarks</th>
                    {% else %}
                    <th scope="col">Status</th>
                    {% endif %}
                  </tr>
                </thead>
               
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Career Talk</td>
                    <td>500</td>
                    <td>money will be used to buy food for school head</td>
                    <td>Agati, Abbygail</td>
                    {% if request.user.is_marketinghead or request.user.is_centermanager %}
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle float-right mr-5 p-1" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             <span class="text"> Remarks </span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="#">Approve</a>
                              <a class="dropdown-item" href="#">Reject</a>
                              <a class="dropdown-item" href="#">Revise</a>
                            </div>
                          </div>
                    </td>
                    {% else %}
                    <td>For Approval</td>
                    {% endif %}
                  </tr>
                </tbody>
              </table> 
            </div>
          </center>


    </div>
</div>
</div>
</div>
<br>



{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

marketinghead/templates/budget/create_budget.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header %}
{% include 'header.html' %}
{% endblock header %}

{% block sidebar %}

{% endblock sidebar %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block title %}
        <title>Marketing | Target Sheet</title>
{% endblock title %}


{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{% url 'crm_blog:home' %}" class="btn btn-primary" > BACK</a>
      
<div class="float-left">
 
</div>
</div>
<!---->
<div class="card">

      <div class="card-body">
    <!-- Start of Breadcrumb -->
    

    
    
    <!-- end -->

<!-- End of Bread Crumb -->
    <br>

<!-- page content -->
    <div class="content-section">
        {% include 'messages.html' %}
       
    <div class="row d-flex justify-content-center" style="min-height:50%;">
 
  

  <!-- Retail -->
  <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">total Budget</div>
                <div class="row no-gutters align-items-center">
                  <div class="col-auto">
                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                       {% for budget_total in budget_total %} 
                        {{ budget_total }}
                      {% endfor %}
                    </div>
                  </div>
                 
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">          

    
        <div class="card-body">
          <form action="" method="POST">                      
                  {% csrf_token %}
                                 
             <fieldset class="form-group" >
                         {{ form|crispy }}
             </fieldset> 
         
             <div class="row float-right " style="padding-right: 5%;">        
                 <div class="form-group ">
                     <button class="btn btn-outline-info" type="submit">Submit</button>                   
                  </div>
                                 &nbsp
             <div class="form-group float-left">            
                 <a href="{% url 'marketing_head:budget_list'%}" class="btn btn-outline-info">
                                 Cancel
                 </a>    
                                 

          </div>  
             </div>
             </div>               
             </form>
           </div>       
    <hr>
    <nav aria-label="Page navigation example" style="margin-button: 1%; padding-left: 84%;">
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </nav> 
      <!---->
      <center>
      <div style="max-width:80%">
        <table class="table table-bordered" style="height: 100%;">
          <thead class="bg-primary text-light">
            <tr>
              <th scope="col">Amount</th>
              <th scope="col">Date of Arrival</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          {% for budget_list in budget_list %}
          <tbody>
              <tr>
                  <th scope="row">{{ budget_list.amount }}</th>
                  <td>{{ budget_list.arrival }}</td>
                  <td>
                    <a href="{% url 'marketing_head:budget_update' budget_list.pk %}" class="btn btn-success" style="padding: 3px;">UPDATE</a>
                  </td>
              </tr>
          </tbody>
          {% endfor %}
        </table> 
      </div>
    </center>
    </div>
</div>
</div>
</div>
<br>















{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}