accounts/urls.py
from django.urls import path



from . import views

app_name="accounts"

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile' ),
    path('add/user/', views.CreateUserView.as_view(), name='create_user'),
    path('user/list/', views.UsersListView.as_view(), name='user_list'),
    path('user/<int:pk>/detail', views.UserDetailView.as_view(), name='user_details'),
    path('user/<int:pk>/edit', views.UpdateUserView.as_view(), name='user_update'),
]

centermanager/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns


from . import views
from . import t_views
from . import s_views
from . import sy_views
app_name = 'centermanager'


urlpatterns = [
    
    path('add/employee/', views.EmployeeRegistration.as_view(), name='add_employee'),
    path('employee/list/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employee/<int:pk>/details/', views.EmployeeDetailView.as_view(), name='employee_detial'),
    path('employee/<int:pk>/edit/', views.EmployeeUpdateView.as_view(), name='employee_update'),
    
#    path('create/payment/', views.PaymentCreateView.as_view(), name='create_payment'),
    path('payment/list/', views.MatriculationTemplateView.as_view(), name='payment_list'),
    path('payment/view/', views.MatriculationListView.as_view(), name='payment_view'),
#    path('payment/<int:pk>/details/', views.PaymentDetailView.as_view(), name='payment_detail'),
    path('payment/<int:pk>/higher-education/nc/edit', views.MatriculationUpdateHENC.as_view(), name='henc_update'),
    path('payment/<int:pk>/higher-education/rc/edit', views.MatriculationUpdateHERC.as_view(), name='herc_update'),
    path('payment/<int:pk>/shs/edit', views.MatriculationUpdateSHS.as_view(), name='shs_update'),
    
    
    
#   path('create/commission/', views.CommissionSettingCreateView.as_view(), name='create_commission'),
    path('commission/list/', views.CommissionSettingListView.as_view(), name='commission_list'),  
#   path('commission/<int:pk>/details/', views.CommissionDetailView.as_view(), name='commission_detial'),
    path('commission/<int:pk>/shs/edit', views.CommissionSettingSHSUpdate.as_view(), name='com_shs_update'),
    path('commission/<int:pk>/higher-education/rc/edit', views.CommissionSettingHERCUpdate.as_view(), name='com_herc_update'),
    path('commission/<int:pk>/higher-education/nc/edit', views.CommissionSettingHENCUpdate.as_view(), name='com_henc_update'),
    path('commission/<int:pk>/icl/edit', views.CommissionSettingICLUpdate.as_view(), name='com_icl_update'),

    
    path('create/sanction/', s_views.SanctionSettingCreateView.as_view(), name='create_sanction'),
    path('sanction/list/', s_views.SanctionSettingListView.as_view(), name='sanction_list'),   
    path('sanction/<int:pk>/details/', s_views.SanctionSettingDetailView.as_view(), name='sanction_detial'),
    path('sanction/<int:pk>/edit/', s_views.SanctionSettingUpdateView.as_view(), name='sanction_update'),


    path('school-year/', sy_views.SchoolYearCreateView.as_view(), name='create_school_year'),
    path('school-year/list/', sy_views.SchoolYearListView.as_view(), name='school_year_list'),
    path('school-year/<int:year>', sy_views.SchoolYearArchiveView.as_view(), name='school_year_archive'),
    
    path('create/target-sheet/', t_views.TargetSheetCreateView.as_view(), name='create_target'),
    path('target-sheet/', t_views.TargetSheetListView.as_view(), name='target'),
    path('target-sheet/<int:pk>/details/', t_views.TargetSheetDetailView.as_view(), name='target_details'),
    path('target-sheet/<int:pk>/edit/', t_views.TargetUpdateView.as_view(), name='target_update'),
         
]




urlpatterns = format_suffix_patterns(urlpatterns)

crm_blog/urls.py
from django.urls import path
from . import views

app_name = 'crm_blog'

urlpatterns = [
    path('home/', views.blog_home_view, name='home'),
]

marketing/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.forms import AuthenticationForm

#from accounts.urls import user_login, user_logout
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard', include( 'jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('marketing/', include('crm_blog.urls'),),
    path('center/', include('centermanager.urls'),),
    path('contacts/', include('contacts.urls')),
    path('accounts/', include('accounts.urls'),),
    path('schedule/', include('activitycalendar.urls')),
    path('marketinghead/', include('marketinghead.urls')),
    path('activity/', include('careerconsultant.urls')),
    path('activity1/', include('activity.urls')),
    path('centerbusinessmanager/', include('centerbusinessmanager.urls')),
    path('registrar/',include('registrar.urls')),
    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

centermanager/views.py
import json

from datetime import date, timedelta
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404

from centermanager.models import (
    MatriculationSeniorHighSchool,
    MatriculationHigherEducationNC,
    MatriculationHigherEducationRC,
    CommissionSettingSHS,
    CommissionSettingHENC,
    CommissionSettingHERC,
    CommissionSettingICL,
    SchoolYear,
    SanctionSetting,
)

from centermanager.forms import (
    MatriculationSHSForm,
    MatriculationHENCForm,
    MatriculationHERCForm,
    CommissionSettingSHSForm,
    CommissionSettingHERCForm,
    CommissionSettingHENCForm,
    CommissionSettingICLForm,
    SanctionSettingForm,
    SchoolYearForm,
)
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.views.generic import (
    CreateView, UpdateView, DetailView, TemplateView, View, ListView)
from django.urls import reverse
from django.db.models import Q
from django.template.loader import render_to_string
from accounts.models import User
from django.views.generic.dates import YearMixin, DateMixin
from centermanager.forms import EmployeeRegistrationForm


class EmployeeListView(TemplateView):
    model = User
    context_object_name = "employee_obj_list"
    template_name = 'employer/employee_list.html'
    
    def get_queryset(self):
        queryset = self.model.objects.all()
        
        request_post = self.request.POST
        if request_post:
            if request_post.get('first_name'):
                queryset = queryset.filter(
                    first_name__icontains=request_post.get('first_name')
                )
                
            if request_post.get('last_name'):
                queryset = queryset.filter(
                    last_name___icontains=request_post.get('last_name')
                )
            
            if request_post.get('email'):
                queryset = queryset.filter(
                    email__icontains=request_post.get('email')
                )
        return queryset.distinct()
    
    def get_context_data(self, **kwargs):
        context = super(EmployeeListView, self).get_context_data(**kwargs)
        context['employee_obj_list'] = self.get_queryset().exclude(is_superuser=True).exclude(is_centermanager=True)
        context['cc_obj_list'] = self.get_queryset().exclude(is_superuser=True).exclude(is_centermanager=True).exclude(is_centerbusinessmanager=True).exclude(is_marketinghead=True).exclude(is_registrar=True)
        context['per_page'] = self.request.POST.get('per_page')    
        context['users'] = User.objects.filter(is_active=True).order_by('email')
        
        search = False
        if (
            self.request.POST.get('first_name') or
            self.request.POST.get('last_name') or
            self.request.POST.get('email')
        ):
            search = True
        context['search'] = search
        return context
    
    def post(self, request, *args ,**kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)
    



class EmployeeRegistration(CreateView):
    model = User
    form_class = EmployeeRegistrationForm
    template_name = 'employer/create_employee.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_centermanager:
            self.users = User.objects.filter(is_active=True).order_by('email')
        else:
            self.users = User.objects.filter(is_centermanager=True).order_by('email')
        return super(EmployeeRegistration, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            employee_obj = form.save(commit=False)
            employee_obj.save()
            
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        employee_obj = form.save(commit=False)

        if self.request.is_ajax():
            return JsonResponse(
                {
                    'error':False,
                }
            )

        if self.request.POST.get("savenewform"):
            return redirect("centermanager:add_employee")
        return redirect("centermanager:employee_list")


    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse(
                {
                    'error':True,
                    'employee_errors': form.errors,
                }
            )
        return self.render_to_response(
            self.get_context_data(form=form)
        )
    
    def get_context_data(self, **kwargs):
        context = super(EmployeeRegistration, self).get_context_data(**kwargs)
        context['employee_form'] = context["form"]
        context['employee_list'] = User.objects.all().exclude(is_superuser=True).exclude(is_centermanager=True)
        context['users'] = self.users
        return context
    

class EmployeeDetailView(DetailView):
    model = User
    context_object_name = "employee_record"
    template_name = 'employer/employee_detail.html'
    
    def get_queryset(self):
        queryset = super(EmployeeDetailView, self).get_queryset(**kwargs)
        return queryset.select_related('email')

    
    def get_context_data(self, **kwargs):
        context = super(EmployeeDetailView, self).get_context_data(**kwargs)
        return context
    
    
class EmployeeUpdateView(UpdateView):
    model = User
    form_class = EmployeeRegistrationForm
    template_name = "employer/create_empoyee.html"
    
    def dispatch(self, request, *args, **kwargs):
        if (self.request.user.is_centerbusinessmanager or
            self.request.user.is_marketinghead or
            self.request.user.is_registrar
            ):
            self.users = User.objects.filter(is_active=True).order_by('email')
        else:
            self.users = User.objects.filter(is_centerbusinessmanager=True,
                                             is_marketinghead=True,
                                             is_registrar=True
                                             )    
        return super(EmployeeUpdateView, self).dispatch(request, *args, **kwargs)
    
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            employee_obj = form.save(commit=False)
            employee_obj.save()

            return self.form_valid(form)
        return self.form_invalid(form)
    
    def form_valid(self, form):
        employee_obj = form.save(commit=False)
        if self.request.is_ajax():
            return JsonResponse({
                'error':False,
            })    
        return redirect('centermanager:employee_list')
    
    
    def form_invalid(self, form):
        
        if self.request.is_ajax():
            return JsonResponse(
                {
                    'error':True,
                    'employee_errors': form.errors
                }
            )
        return self.render_to_response(
            self.get_context_data(form=form)
        )
    
    def get_context_data(self, **kwargs):
        context = super(EmployeeUpdateView, self).get_context_data(**kwargs)
        context['employee_obj'] = self.object
        context['employee_form'] = context['form']
        
        return context
    
 


'''Payment Details '''

class MatriculationTemplateView(TemplateView):
    template_name = 'payment/payment_list.html'    
    
    def get_context_data(self, **kwargs):
        context = super(MatriculationTemplateView, self).get_context_data(**kwargs)
        context["shs_list"] = MatriculationSeniorHighSchool.objects.all()
        context["he_nc_list"] = MatriculationHigherEducationNC.objects.all()
        context["he_rc_list"] = MatriculationHigherEducationRC.objects.all()
        return context
    
class MatriculationListView(ListView):
    template_nmae = 'payment/payment_view.html'
    
    def get_context_data(self, **kwargs):
        context = super(MatriculationListView, self).get_context_data(**kwargs)
        context["shs"] = MatriculationSeniorHighSchool.objects.all()
        context["he_nc"] = MatriculationHigherEducationNC.objects.all()
        context["he_rc"] = MatriculationHigherEducationRC.objects.all()
        return context
    

class MatriculationUpdateSHS(UpdateView):
    model = MatriculationSeniorHighSchool
    form_class = MatriculationSHSForm
    template_name = 'payment/shs_payment.html'
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            shs_obj = form.save(commit=False)
            shs_obj.save()
            
            return self.form_valid(form)
        return self.form_invalid(form)
    
    
    def form_valid(self, form):
        if self.request.is_ajax():
            return JsonResponse(
                {
                    'error': True,
                }
            )
        return redirect('centermanager:payment_list')
    
    
    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse(
                {
                    'error':True,
                    'shs_errors': form.errors,
                }
            )
        return self.render_to_response(
            self.get_context_data(form=form)
        )
           
    def get_context_data(self, **kwargs):
        context = super(MatriculationUpdateSHS, self).get_context_data(**kwargs)
        context["shs_obj"] = self.object
        context["shs_form"] = context['form'] 
        return context
    
class MatriculationUpdateHENC(UpdateView):
    model = MatriculationHigherEducationNC
    form_class = MatriculationHENCForm
    template_name = 'payment/henc_payment.html'
    

centermanager/templates/commission/commission_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block header %}
    {% include 'header.html' %}
{% endblock header %}



{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}


{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

centermanager/templates/commission/commission_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block header %}
{% include 'header.html' %}
{% endblock header %}

{% block sidebar %}

{% endblock sidebar %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block title %}
<title>Marketing | Target Sheet</title>
{% endblock title %}


{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{% url 'crm_blog:home' %}" class="btn btn-primary"> BACK</a>

        <div class="float-left">

        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'centermanager:school_year_list' %}">School Year</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'centermanager:target' %}">Target Sheet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'centermanager:payment_list' %}">Matriculation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'centermanager:sanction_list' %}">Sanction</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'centermanager:commission_list' %}">Commission</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <br>
            <div class="content-section">
                {% include 'messages.html' %}

                <div class="card-deck">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-m font-weight-bold text-uppercase mb-1 text-primary">Senior High School</h5>
                                <br>
                                {% for shs in commission_shs_list %}
                                <div style="margin-right: 2%; margin-left: 2%;">
                                    <table class="table table-bordered" style="height: 100%;">
                                        <thead class="bg-primary text-light">
                                            <tr>
                                                <th scope="col">Commission Name</th>
                                                <th scope="col">Specification</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Count per Student</td>
                                                <td>{{ shs.student }}</td>
                                            </tr>
                                            <tr>
                                                <td>Enrolled</td>
                                                <td>{{ shs.student_choices }}</td>
                                            </tr>
                                            <tr>
                                                <td>Tuition Fee</td>
                                                <td>{{ shs.tuition_fee }}</td>
                                            </tr>
    
                                        </tbody>
                                    </table>
                                </div>
                                <a class="btn btn-primary float-right"
                                    href="{% url 'centermanager:com_shs_update' shs.pk %}">Edit</a>
    
                                {% endfor %}
    
                            </div>
                        </div>
                        <!--------------------------------------------------------------------------------------------------------------------------------------------->
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-m font-weight-bold text-uppercase mb-1 text-primary">Higher
                                    Education(Regular Class)</h5>
                                <br>
                                {% for shs in commission_herc_lst %}
                                <div style="margin-right: 2%; margin-left: 2%;">
                                    <table class="table table-bordered" style="height: 100%;">
                                        <thead class="bg-primary text-light">
                                            <tr>
                                                <th scope="col">Commission Name</th>
                                                <th scope="col">Specification</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Count per Student</td>
                                                <td>{{ shs.student }}</td>
                                            </tr>
                                            <tr>
                                                <td>Enrolled</td>
                                                <td>{{ shs.student_choices }}</td>
                                            </tr>
                                            <tr>
                                                <td>Tuition Fee</td>
                                                <td>{{ shs.tuition_fee }}</td>
                                            </tr>
    
                                        </tbody>
                                    </table>
                                </div>
                                <a class="btn btn-primary float-right" href="{% url 'centermanager:com_herc_update' shs.pk %}">Edit</a>
    
                                {% endfor %}
                            </div>
                        </div>
                        <!--------------------------------------------------------------------------------------------------------------------------------------------->
    
                    </div>
                    <br>
                    <div class="card-deck">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-m font-weight-bold text-uppercase mb-1 text-primary">Higher Education (Night
                                    Class)</h5>
                                <br>
                                {% for shs in commission_henc_lst %}
                                <div style="margin-right: 2%; margin-left: 2%;">
                                    <table class="table table-bordered" style="height: 100%;">
                                        <thead class="bg-primary text-light">
                                            <tr>
                                                <th scope="col">Commission Name</th>
                                                <th scope="col">Specification</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Count per Student</td>
                                                <td>{{ shs.student }}</td>
                                            </tr>
                                            <tr>
                                                <td>Enrolled</td>
                                                <td>{{ shs.student_choices }}</td>
                                            </tr>
                                            <tr>
                                                <td>Tuition Fee</td>
                                                <td>{{ shs.tuition_fee }}</td>
                                            </tr>
    
                                        </tbody>
                                    </table>
                                </div>
                                <a class="btn btn-primary float-right" href="{% url 'centermanager:com_henc_update' shs.pk %}">Edit</a>
    
                                {% endfor %}
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-m font-weight-bold text-uppercase mb-1 text-primary">Informatics Corporate
                                    Learning</h5>
                                <br>
                                {% for shs in commission_icl_lst %}
                                <div style="margin-right: 2%; margin-left: 2%;">
                                    <table class="table table-bordered" style="height: 100%;">
                                        <thead class="bg-primary text-light">
                                            <tr>
                                                <th scope="col">Commission Name</th>
                                                <th scope="col">Specification</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Total Collection</td>
                                                <td>{{ shs.total_collection }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <a class="btn btn-primary float-right" href="{% url 'centermanager:com_icl_update' shs.pk %}">Edit</a>
    
                                {% endfor %}
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

centermanager/templates/commission/create_commission.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block header %}
{% include 'header.html' %}
{% endblock header %}

{% block sidebar %}

{% endblock sidebar %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block title %}
        <title>Marketing | Commission</title>
{% endblock title %}


{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">

    <!-- Start of Breadcrumb -->
    <nav aria-label="breadcrumb" class="row" style="padding-left:1%;">
        <h4>Commission</h4>   
<!-- search field -->
    <div class="topbar-divider d-none d-sm-block" style="padding-right:71%"></div>
 <div class="input-group float-right" style="max-width: 20%;">            
            <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="addon-wrapping">
            <div class="input-group-prepend" >
              <span class="input-group-text"  style="background-color: 0080ff;"><i class="fas fa-search"></i></span>
            </div>
          </div>                
    </nav>
    
    <!-- End of Bread Crumb -->
    <br>

<!-- page content -->
    <div class="content-section">
        {% include 'messages.html' %}
    

<!-- DIV FOR ADDING SANCTION-->

  
<div class="card card-deck float-left" style="min-width:30%; max-width:30%; "> 
    <!-- BUTTON ADD SANCTION-->
    <div class="card-body">          

           <div class="card-body">
             <form action="" method="POST">                      
                     {% csrf_token %}
                                    
                <fieldset class="form-group" >
                            {{ form|crispy }}
                </fieldset> 
            
                <div class="row float-right " style="padding-right: 5%;">        
                    <div class="form-group ">
                        <button class="btn btn-outline-info" type="submit">Submit</button>                   
                     </div>
                                    &nbsp
                <div class="form-group float-left">
                    <a href="{% url 'centermanager:commission_list'%}" class="btn btn-outline-info">
                                    Cancel
                    </a>    
             </div>  
                </div>
                </div>               
                </form>
              </div>                   
        </div>

<!-- DIV THAT SHOWS ALL THE ADDED SANCTION-->       
<div class=" card card-deck float-right" style="min-height:560px; min-width: 70%; max-width: 70%; ">
    
        <div class="row mx-3 my-3">
                <div class="card border-primary " >
                <div class="card-body text-primary">
                <div class="card-title">Senior High School</div>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
                </div>
                <div class="card border-primary " >
                <div class="card-body text-primary">                                 
                    <div class="card-title">Informatics Corporate Learning</div>                                
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
                </div>
                                      
                        
            <div class="row  mx-3 mb-3">
                    <div class="card border-primary " >
                        <div class="card-body text-primary">
                        <div class="card-title">Informatics Higher Education: Regular Class</div>                                                 
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                        </div>

                        <div class="card border-primary " >
                                <div class="card-body text-primary">
                                <div class="card-title">Infortmatics Higher Education: Night Class</div>                                                 
                                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                                </div>
            </div>            
            </div>
</div> 
<br><br>


</div>
    </div>
</div>
<br>


{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}